name = "my-worker"
main = "./index.ts"
type = "typescript"  
compatibility_date = "2026-03-10"
account_id="0716831789a537e6b14a15b1060e3f33"

[[d1_databases]]
binding = "DB"
database_name = "ebsm"
database_id = "9e65544a-3adc-40bf-a7ca-01cb999de407"