/* eslint-disable import/no-anonymous-default-export */
/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
} from "vinext/server/image-optimization";
import { createClerkClient } from "@clerk/backend";
import handler from "vinext/server/app-router-entry";

type Fetcher = {
  fetch(request: Request): Response | Promise<Response>;
};

interface Env {
  ASSETS: Fetcher;
  CLERK_SECRET_KEY: string;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: {
          format: string;
          quality: number;
        }): Promise<{ response(): Response }>;
      };
    };
  };
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
}

const protectedRoutes = [
  /^\/dashboard(?:\/|$)/,
  /^\/profile(?:\/|$)/,
  /^\/requests(?:\/|$)/,
  /^\/help(?:\/|$)/,
  /^\/admin(?:\/|$)/,
];
const managerRoutes = [/^\/admin(?:\/|$)/];

function isManagerRole(role: unknown): boolean {
  return (
    role === "admin" ||
    role === "hr" ||
    role === "hr_admin" ||
    role === "finance_manager" ||
    role === "finance"
  );
}

function getMissingClerkKeys(env: Env): string[] {
  return [
    env.CLERK_SECRET_KEY ? null : "CLERK_SECRET_KEY",
    env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ? null : "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
  ].filter((value): value is string => value != null);
}

function renderMissingConfigResponse(missingKeys: string[]): Response {
  const items = missingKeys.map((key) => `<li><code>${key}</code></li>`).join("");

  return new Response(
    `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Missing Clerk Configuration</title>
    <style>
      :root {
        color-scheme: light;
        font-family: ui-sans-serif, system-ui, sans-serif;
      }
      body {
        margin: 0;
        min-height: 100vh;
        display: grid;
        place-items: center;
        background: #f8fafc;
        color: #0f172a;
      }
      main {
        width: min(32rem, calc(100vw - 2rem));
        padding: 1.5rem;
        background: #fff;
        border: 1px solid #e2e8f0;
        border-radius: 1rem;
        box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08);
      }
      h1 {
        margin: 0;
        font-size: 1.25rem;
      }
      p {
        margin: 0.75rem 0 0;
        line-height: 1.5;
      }
      ul {
        margin: 1rem 0 0;
        padding-left: 1.25rem;
      }
      code {
        font-family: ui-monospace, SFMono-Regular, monospace;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>Missing Clerk configuration</h1>
      <p>Protected routes cannot be opened until these environment variables are set:</p>
      <ul>${items}</ul>
    </main>
  </body>
</html>`,
    {
      status: 503,
      headers: {
        "content-type": "text/html; charset=UTF-8",
      },
    },
  );
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (protectedRoutes.some((pattern) => pattern.test(url.pathname))) {
      const missingClerkKeys = getMissingClerkKeys(env);

      if (missingClerkKeys.length > 0) {
        return renderMissingConfigResponse(missingClerkKeys);
      }

      const clerk = createClerkClient({
        secretKey: env.CLERK_SECRET_KEY,
        publishableKey: env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
      });

      const authState = await clerk.authenticateRequest(request);

      if (!authState.isAuthenticated) {
        const loginUrl = new URL("/login", request.url);
        loginUrl.searchParams.set("redirect_url", `${url.pathname}${url.search}`);
        return Response.redirect(loginUrl, 307);
      }

      if (managerRoutes.some((pattern) => pattern.test(url.pathname))) {
        const auth = authState.toAuth();

        if (!auth.userId) {
          return Response.redirect(new URL("/dashboard", request.url), 307);
        }

        const user = await clerk.users.getUser(auth.userId);

        if (!isManagerRole(user.publicMetadata?.role)) {
          return Response.redirect(new URL("/dashboard", request.url), 307);
        }
      }
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(
        request,
        {
          fetchAsset: async (path: string) =>
            env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (
            body: ReadableStream<Uint8Array>,
            {
              width,
              format,
              quality,
            }: { width: number; format: string; quality: number },
          ) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality });
            return result.response();
          },
        },
        allowedWidths,
      );
    }

    // Delegate everything else to vinext
    return handler.fetch(request);
  },
};
