/* eslint-disable import/no-anonymous-default-export */
/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
} from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

type Fetcher = {
  fetch(request: Request): Promise<Response>;
};

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: {
          format: string;
          quality: number;
        }): Promise<{ response(): Response }>;
      };
    };
  };
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      try {
        return await handleImageOptimization(
          request,
          {
            fetchAsset: async (path: string, sourceRequest: Request) =>
              env.ASSETS.fetch(new Request(new URL(path, sourceRequest.url))),
            transformImage: async (
              body: ReadableStream<Uint8Array>,
              {
                width,
                format,
                quality,
              }: { width: number; format: string; quality: number },
            ) => {
              const result = await env.IMAGES.input(body)
                .transform(width > 0 ? { width } : {})
                .output({ format, quality });
              return result.response();
            },
          },
          allowedWidths,
        );
      } catch (error) {
        console.error("[worker] image optimization failed", error);
        return new Response("Image optimization failed", { status: 500 });
      }
    }

    // Delegate everything else to vinext
    try {
      return await Promise.race<Response>([
        handler.fetch(request),
        new Promise<Response>((resolve) => {
          setTimeout(() => {
            resolve(
              new Response("Request timeout in worker runtime", { status: 504 }),
            );
          }, 15000);
        }),
      ]);
    } catch (error) {
      console.error("[worker] unhandled fetch error", error);
      return new Response("Internal worker error", { status: 500 });
    }
  },
};
